library(limma)

GEOPipelineLimma <- function(relev.eset){
  #This function will run the appropriate limma functions on an expression set list generated through the GEO pipeline
  #and return the output of the analysis as an MArrayLM object generated by the eBayes function.
  #typeof(relev.eset) == expressionSet. This should be the eset of interest. 
  #If using LimmaGeneric, read the following:
  #One or more columns in pData should start with CONTRAST_.These should have 1's indicating which rows are included 
  #in the numerator of the contrast and -1's indicating which rows are included in the denominator of that contrast. 
  #There should only be one contrast marked per CONTRAST_ column.
  
  #check if there is a specific limma function for this dataset
  relev.eset.limma.func <- paste0("Limma_", notes(relev.eset)$name)
  if (exists(relev.eset.limma.func)) {
    limma.func.name <- relev.eset.limma.func
  }else{limma.func.name <- "LimmaGeneric"}
  #if there is a specific function, run it; if not, run generic
  eFits <- eval(parse(text=paste0(limma.func.name,"(relev.eset)")))
  return(eFits)
}

LimmaGeneric <- function(relev.eset){
  #typeof(relev.eset) == expressionSet. This is the eset of interest.
  
  #locate columns which delineate contrasts
  contrast.cols <- grep("^CONTRAST_", colnames(pData(relev.eset)), value=TRUE)
  #create list which holds results
  eFit.res <- list()
  for (contrast in 1:length(contrast.cols)){
    #create model matrix for this contrast
    design <- model.matrix(~0+group, data.frame(group=c("denominator", "other", "numerator")
                                                [pData(relev.eset)[,contrast.cols[contrast]]+2]))
    #remove odd model matrix output where the name used as the first input in model.matrix is added
    #to the beginning of the given column names in the data argument of model.matrix
    colnames(design) <- sub("group", "",colnames(design))
    fit <- lmFit(relev.eset, design)
    #try to run contrast; if unsuccessful, return error and go on to the next contrast  
    contrast.eFit <- tryCatch({
      RunContrasts(contrast.cols[contrast], design, fit)
    }, error = function(err){
      print(paste("Error:", err))
      print(paste("An error occurred. Contrast ", contrast.cols[contrast], "will not be calculated."))
      return(err)
    })
      #add results from each comparison to the final results list
    eFit.res[[contrast]] <- contrast.eFit
    names(eFit.res)[contrast] <- contrast.cols[contrast]
  }
  return(eFit.res)
}

RunContrasts <- function(contrast.column, design.mat,linfit){
  #typeof(contrast.column) == string. This is the name of the column that holds the designation for which samples should
  #be compared in the contrast.
  #typeof(design.mat) == matrix. This is the model/design matrix for the linear fit model for the eset of interest.
  #typeof(linfit) == MArrayLM. This is a linear model fit of the eset.
  
  #create contrast matrix to run appropriate analyses
  contrast.matrix <- matrix(0, nrow=ncol(design.mat), ncol=1, 
                            dimnames=list(colnames(design.mat), "Contrast Value"))
  contrast.matrix["denominator", 1] <- -1
  contrast.matrix["numerator", 1] <- 1
  tmp.fit <- contrasts.fit(linfit, contrast.matrix)
  tmp.eFit <- eBayes(tmp.fit)
  return(tmp.eFit)
}
